### PR TITLE
Support bare workflow in newer Expo/RN versions (close #182)

### LINKED ISSUE #182: Support bare workflow in newer Expo/RN versions
The issue was identified and a fix was contributed by @Jeroen-G.

When installing the package in an app with RN 0.68.2 and Expo 45, the builds for iOS fail with this error (besides for `RCTBundleManager` also for a few others):

```
Duplicate interface definition for class 'RCTBundleManager'

in file included from [...]/node_modules/@snowplow/react-native-tracker/ios/RNSnowplowTracker.m:21:
in file included from [...]/node_modules/@snowplow/react-native-tracker/ios/RNSnowplowTracker.h:28:
```

Similar issues in other packages:

- https://github.com/expo/expo/issues/15649
- https://github.com/expo/expo/issues/15622
- https://github.com/segmentio/analytics-react-native/pull/434

### PR DESCRIPTION
**Pull request by Jeroen-G**
Disclaimer: to be honest, I do not fully understand why it only works this way.

I am building an app with RN 0.68.2 and Expo 45. I wanted to install the Snowplow package but the builds for iOS fail with this error (besides for `RCTBundleManager` also for a few others):

```
Duplicate interface definition for class 'RCTBundleManager'

in file included from [...]/node_modules/@snowplow/react-native-tracker/ios/RNSnowplowTracker.m:21:
in file included from [...]/node_modules/@snowplow/react-native-tracker/ios/RNSnowplowTracker.h:28:
```

Based on what I learned from similar issues in other packages I have made the changes in this PR and tested them with my app.

- https://github.com/expo/expo/issues/15649
- https://github.com/expo/expo/issues/15622
- https://github.com/segmentio/analytics-react-native/pull/434

### CODE REVIEW

**Comment by colmsnowplow** [comment]
If memory serves originally in this project we couldn't support expo at all, since they it support native modules at the time. It's been a while since I've been involved in this project but awsome to see that's changed - thanks for bringing that to our attention @Jeroen-G!

**Comment by Jeroen-G** [comment]
@colmsnowplow I don't want to diminish your enthousiasm, but Expo does not _really_ support native modules 😅  We use the 'bare workflow' from expo, meaning that we 'ejected' from the Expo bubble and allowing the installation of native modules. Nevertheless, we still rely heavily on Expo packages.

**Comment by paulboocock** [comment]
Hi @Jeroen-G 

Thanks for the PR. We'll get someone to take a deeper look at this and Expo support shortly, but in the meantime could you sign our CLA so we could merge this? It looks like our CLA bot has gone walkabouts!

--------

Thanks for your pull request. Is this your first contribution to a Snowplow open source project? Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

📝 Please visit https://docs.snowplowanalytics.com/docs/contributing/contributor-license-agreement/ to learn more and sign.

Once you've signed, please reply here (e.g. I signed it!) and we'll verify. Thanks.

**Review by matus-tomlein — APPROVED** [review]
LGTM!

@Jeroen-G please sign the CLA and I'll make sure this gets to the next release of the package that will be released very soon!

**Comment by Jeroen-G** [comment]
I don't feel comfortable giving my personal details, therefore I will not sign the CLA. Feel free to do with the contribution what you like :)

**Comment by AlexBenny** [comment]
Hi @Jeroen-G,

Thanks again for raising this issue and the PR!
I'm sorry to hear that our CLA makes you uncomfortable to contribute. We'll raise your concerns internally in order to see if we can handle the CLA differently. In any case, it can be a long process. We'll keep you updated about any decision about this PR and the CLA issue.

**Pull request closed without merging**
